/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as faucetSol from "./Faucet.sol";
export type { faucetSol };
import type * as onchainScoreSol from "./OnchainScore.sol";
export type { onchainScoreSol };
import type * as safuTokenSol from "./SafuToken.sol";
export type { safuTokenSol };
import type * as sawiTokenSol from "./SawiToken.sol";
export type { sawiTokenSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { CreditScoreNFT } from "./CreditScoreNFT";
export type { Savings } from "./Savings";
