/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as faucetSol from "./Faucet.sol";
export * as onchainScoreSol from "./OnchainScore.sol";
export * as safuTokenSol from "./SafuToken.sol";
export * as sawiTokenSol from "./SawiToken.sol";
export * as interfaces from "./interfaces";
export { CreditScoreNFT__factory } from "./CreditScoreNFT__factory";
export { Savings__factory } from "./Savings__factory";
